### ISSUE TITLE
Linux compatibility (with a patch)

### ISSUE THREAD

**Issue by tapio** [BKcore/JungleIN#1]
Hi, I did the following trivial thing to get this building (and running!) on Ubuntu 12.04. It's doesn't attempt anything fancy, but as most Linuxes have libs and headers in standard places, it just works.

```
diff --git a/trunk/JungleIN.pro b/trunk/JungleIN.pro
index 2dc3eb3..a0be107 100644
--- a/trunk/JungleIN.pro
+++ b/trunk/JungleIN.pro
@@ -10,6 +10,7 @@ TEMPLATE = app
 DEPENDPATH += src
 INCLUDEPATH = src "D:\System\QtSDK\glew-1.5.4-mingw32\include"
 win32:LIBS += -L"D:\System\QtSDK\glew-1.5.4-mingw32\lib" -lglew32
+unix:LIBS += -lGLEW

 DESTDIR = release
 OBJECTS_DIR = obj
```

**Comment by BKcore** [comment]
Thank you for this little patch. https://github.com/BKcore/JungleIN/commit/03ceaf069cb7bbd6704258111dcc83f0782cbe8d
